/*
Deployment script for RetailStaging

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "RetailStaging"
:setvar DefaultFilePrefix "RetailStaging"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping Check Constraint unnamed constraint on [dbo].[DimDate]...';


GO
ALTER TABLE [dbo].[DimDate] DROP CONSTRAINT [CK__DimDate__SourceS__0F624AF8];


GO
PRINT N'Dropping Check Constraint unnamed constraint on [dbo].[DimProduct]...';


GO
ALTER TABLE [dbo].[DimProduct] DROP CONSTRAINT [CK__DimProduc__Sourc__10566F31];


GO
PRINT N'Dropping Check Constraint unnamed constraint on [dbo].[DimSalesRep]...';


GO
ALTER TABLE [dbo].[DimSalesRep] DROP CONSTRAINT [CK__DimSalesR__Sourc__14270015];


GO
PRINT N'Dropping Check Constraint unnamed constraint on [dbo].[DimStore]...';


GO
ALTER TABLE [dbo].[DimStore] DROP CONSTRAINT [CK__DimStore__Source__160F4887];


GO
PRINT N'Dropping Check Constraint unnamed constraint on [dbo].[DimCustomer]...';


GO
ALTER TABLE [dbo].[DimCustomer] DROP CONSTRAINT [CK__DimCustom__Sourc__1332DBDC];


GO
PRINT N'Dropping Check Constraint unnamed constraint on [dbo].[DimCustomer]...';


GO
ALTER TABLE [dbo].[DimCustomer] DROP CONSTRAINT [CK__DimCustom__Gende__114A936A];


GO
PRINT N'Creating Check Constraint unnamed constraint on [dbo].[DimDate]...';


GO
ALTER TABLE [dbo].[DimDate] WITH NOCHECK
    ADD CHECK (SourceSystem IN ('POS','ERP','CRM','CSV'));


GO
PRINT N'Creating Check Constraint unnamed constraint on [dbo].[DimProduct]...';


GO
ALTER TABLE [dbo].[DimProduct] WITH NOCHECK
    ADD CHECK (SourceSystem IN ('POS','ERP','CRM','CSV'));


GO
PRINT N'Creating Check Constraint unnamed constraint on [dbo].[DimSalesRep]...';


GO
ALTER TABLE [dbo].[DimSalesRep] WITH NOCHECK
    ADD CHECK (SourceSystem IN ('POS','ERP','CRM','CSV'));


GO
PRINT N'Creating Check Constraint unnamed constraint on [dbo].[DimStore]...';


GO
ALTER TABLE [dbo].[DimStore] WITH NOCHECK
    ADD CHECK (SourceSystem IN ('POS','ERP','CRM','CSV'));


GO
PRINT N'Creating Check Constraint unnamed constraint on [dbo].[DimCustomer]...';


GO
ALTER TABLE [dbo].[DimCustomer] WITH NOCHECK
    ADD CHECK (Gender IN ('M','F'));


GO
PRINT N'Creating Check Constraint unnamed constraint on [dbo].[DimCustomer]...';


GO
ALTER TABLE [dbo].[DimCustomer] WITH NOCHECK
    ADD CHECK (SourceSystem IN ('POS','ERP','CRM','CSV'));


GO
-- post-deploy stub
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
CREATE TABLE [#__checkStatus] (
    id           INT            IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
    [Schema]     NVARCHAR (256),
    [Table]      NVARCHAR (256),
    [Constraint] NVARCHAR (256)
);

SET NOCOUNT ON;

DECLARE tableconstraintnames CURSOR LOCAL FORWARD_ONLY
    FOR SELECT SCHEMA_NAME([schema_id]),
               OBJECT_NAME([parent_object_id]),
               [name],
               0
        FROM   [sys].[objects]
        WHERE  [parent_object_id] IN (OBJECT_ID(N'dbo.DimDate'), OBJECT_ID(N'dbo.DimProduct'), OBJECT_ID(N'dbo.DimSalesRep'), OBJECT_ID(N'dbo.DimStore'), OBJECT_ID(N'dbo.DimCustomer'))
               AND [type] IN (N'F', N'C')
                   AND [object_id] IN (SELECT [object_id]
                                       FROM   [sys].[check_constraints]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0
                                       UNION
                                       SELECT [object_id]
                                       FROM   [sys].[foreign_keys]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0);

DECLARE @schemaname AS NVARCHAR (256);

DECLARE @tablename AS NVARCHAR (256);

DECLARE @checkname AS NVARCHAR (256);

DECLARE @is_not_trusted AS INT;

DECLARE @statement AS NVARCHAR (1024);

BEGIN TRY
    OPEN tableconstraintnames;
    FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
    WHILE @@fetch_status = 0
        BEGIN
            PRINT N'Checking constraint: ' + @checkname + N' [' + @schemaname + N'].[' + @tablename + N']';
            SET @statement = N'ALTER TABLE [' + @schemaname + N'].[' + @tablename + N'] WITH ' + CASE @is_not_trusted WHEN 0 THEN N'CHECK' ELSE N'NOCHECK' END + N' CHECK CONSTRAINT [' + @checkname + N']';
            BEGIN TRY
                EXECUTE [sp_executesql] @statement;
            END TRY
            BEGIN CATCH
                INSERT  [#__checkStatus] ([Schema], [Table], [Constraint])
                VALUES                  (@schemaname, @tablename, @checkname);
            END CATCH
            FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
        END
END TRY
BEGIN CATCH
    PRINT ERROR_MESSAGE();
END CATCH

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') >= 0
    CLOSE tableconstraintnames;

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') = -1
    DEALLOCATE tableconstraintnames;

SELECT N'Constraint verification failed:' + [Schema] + N'.' + [Table] + N',' + [Constraint]
FROM   [#__checkStatus];

IF @@ROWCOUNT > 0
    BEGIN
        DROP TABLE [#__checkStatus];
        RAISERROR (N'An error occurred while verifying constraints', 16, 127);
    END

SET NOCOUNT OFF;

DROP TABLE [#__checkStatus];


GO
PRINT N'Update complete.';


GO
